name: weather
description: "A new weather app."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any # An exact version pin will be provided by the Flutter SDK
  cupertino_icons: ^1.0.2
  http: ^1.2.0
  provider: ^6.1.2
  mockito: ^5.4.4
  shared_preferences: ^2.2.2
  adaptive_breakpoints_freezed: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  very_good_analysis: ^5.1.0
flutter:
  uses-material-design: true
  generate: true
